### ISSUE TITLE
Is the websocket lib client capable?

### ISSUE THREAD

**Issue by keyle** [onionhammer/onion-nimrod#4]
Hi

I'm trying to write a websocket **client** in nim. I tried my own luck with the RFC and the sockets but I'm having difficulties. I stumbled upon your code.

Can your websocket code run as a client or it's purely a server implementation?

If not, what other lib should I look at (language agnostic) to translate over?

thanks

**Comment by onionhammer** [comment]
It's server-side only, but doing client-side shouldnt be much more difficult. I'm not aware of any open source implementations, but I'm sure they're out there.
